### ISSUE TITLE
Uncaught TypeError when searching for a file

### ISSUE THREAD

**Issue by igor10k** [fentas/atom-to-base64#1]
1. Press ⌘⇧P
2. Type insert and press ↩
3. Type anything. In my case it was "logo".

**Atom Version**: 1.0.0
**System**: Mac OS X 10.11
**Thrown From**: [to-base64](https://github.com/fentas/atom-to-base64) package, v0.4.1
### Stack Trace

Uncaught TypeError: Arguments to path.resolve must be strings

```
At path.js:400

TypeError: Arguments to path.resolve must be strings
  at Object.posix.resolve (path.js:400:13)
  at new PathScanner (/Users/igor1043k/.atom/packages/to-base64/lib/path-scanner.coffee:54:22)
  at Function.<anonymous> (/Users/igor1043k/.atom/packages/to-base64/lib/to-base64-insert-view.coffee:109:27)
  at Function.View.buildHtml (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:123:10)
  at Function.View.render (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:129:19)
  at exports.$$ (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:627:24)
  at ToBase64InsertView.module.exports.ToBase64InsertView.viewForItem (/Users/igor1043k/.atom/packages/to-base64/lib/to-base64-insert-view.coffee:45:5)
  at ToBase64InsertView.module.exports.SelectListView.populateList (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:206:29)
  at ToBase64InsertView.module.exports.ToBase64InsertView.populateList (/Users/igor1043k/.atom/packages/to-base64/lib/to-base64-insert-view.coffee:146:5)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:350:26

```
### Commands

```
     -0:17.2.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:16.8.0 core:undo (atom-text-editor.editor.is-focused)
     -0:16.4.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:15.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:14.1.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:13.8.0 core:undo (atom-text-editor.editor.is-focused)
     -0:11.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:10.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:10.5.0 to-base64:insert (atom-text-editor.editor)
     -0:08.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-one-dark-ui)
     -0:05.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:05.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:04.8.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-one-dark-ui)
     -0:03.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.6.0 to-base64:insert (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "useReactEditor": true,
    "disabledPackages": [
      "custom-title",
      "term2",
      "term",
      "Sublime-Style-Column-Selection",
      "Zen",
      "maximize-panes",
      "autocomplete-sass"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.6
atom-ternjs, v0.6.4
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.6
autocomplete-ruby, v0.1.0
clipboard-history, v0.6.6
color-picker, v2.0.7
editorconfig, v1.0.0
emmet, v2.3.10
file-icons, v1.5.8
highlight-selected, v0.10.1
linter, v1.0.6
linter-coffeelint, v0.3.2
linter-haml, v0.4.0
linter-jshint, v0.1.7
linter-php, v0.0.15
linter-rubocop, v0.2.7
minimap, v4.10.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
minimap-linter, v0.1.0
minimap-pigments, v0.1.1
minimap-selection, v4.2.0
monokai, v0.14.0
pigments, v0.8.0
symbols-tree-view, v0.9.3
terminal-status, v1.6.8
to-base64, v0.4.1

# Dev
No dev packages
```

**Comment by fentas** [comment]
Thanks for sharing. I will look into it as soon as possible.

**Comment by fentas** [comment]
Publishing to-base64@v0.4.2 ✓

thanks again. If it's not solved feel free to comment again. : )

**Comment by igor10k** [comment]
thanks, no more errors!

Did you try to implement partial search? Currently I have to fully type the image name to choose it. It would be nice to just type just some of its letters instead.

**Comment by fentas** [comment]
I thought about it too.
Atm you can use glob search as described on start up of the insert command.
Like `*.jpg` or `[image_name]*`. Maybe it's not that intuitive? ,)

What I also added with this patch was that you see the path of the match. 
Got confusing if you see only the file name and didn't know where it is. 

Hope this helps.

**Comment by igor10k** [comment]
Heh, yeah, by default Atom searches in file picker using fuzzy logic. So that you can type `hdr` and find **h**ea**d**e**r**. Probably the most intuitive would be to use the same logic in plugins too.
