### ISSUE TITLE
Base64 insert (css: url(...))

### ISSUE THREAD

**Issue by fentas** [fentas/atom-to-base64#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Ubuntu 14.04.3
**Thrown From**: [to-base64](https://github.com/fentas/atom-to-base64) package, v0.4.2
### Stack Trace

Uncaught ReferenceError: i is not defined

```
At /home/user/github/to-base64/lib/to-base64-insert-as-view.coffee:22

ReferenceError: i is not defined
  at ToBase64.<anonymous> (/home/user/github/to-base64/lib/to-base64-insert-as-view.coffee:22:72)
  at IncomingMessage.<anonymous> (/home/user/github/to-base64/lib/to-base64-core.coffee:56:18)
  at emitOne (events.js:77:13)
  at IncomingMessage.emit (events.js:166:7)
  at IncomingMessage.Readable.read (_stream_readable.js:356:10)
  at flow (_stream_readable.js:734:26)
  at resume_ (_stream_readable.js:714:3)
  at _stream_readable.js:701:7
  at process._tickCallback (node.js:357:13)

```
### Commands

```
     -0:46.8.0 core:undo (atom-text-editor.editor.is-focused)
     -0:45.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:43.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:40.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:40.3.0 to-base64:encode (atom-text-editor.editor)
     -0:38 core:undo (atom-text-editor.editor.is-focused)
     -0:17.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:15.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:12.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:12.2.0 to-base64:encode (atom-text-editor.editor)
  2x -0:10 core:undo (atom-text-editor.editor.is-focused)
     -0:07.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:05.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:05.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.5.0 to-base64:insert (atom-text-editor.editor)
     -0:01.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "test"
    ]
  },
  "to-base64": {
    "mtypes": {
      "application": {
        "font-woff": {
          "css": {},
          "data": {}
        },
        "x-font-ttf": {
          "css": {},
          "data": {}
        }
      },
      "image": {
        "_": {
          "css": {},
          "data": {},
          "xhtml": {}
        }
      }
    }
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.14
editor-stats, v0.17.0
file-icons, v1.6.9
git-control, v0.3.0
linter, v1.6.0
linter-jshint, v1.2.0
project-manager, v2.5.2
tabs-to-spaces, v0.11.1
to-base64, v0.4.2
travis-ci-status, v0.18.0
tree-view-git-branch, v0.0.3

# Dev
No dev packages
```

**Comment by fentas** [comment]
fixed with version v0.5.1 :+1:
