### ISSUE TITLE
Error updating to 0.5.x - oniguruma

### ISSUE THREAD

**Issue by brusser** [fentas/atom-to-base64#5]
See console output below. Seems to be an error with oniguruma install. Teh debug log file listed in the output does not exist. The temp install directory is cleaned up after install it seems.

No problems with installing version 0.4.2. I performed a complete uninstall / reinstall and it still did not work.

```
> atom --version
Atom    : 1.12.5
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

```
>apm --version
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.10.2.windows.1
visual studio
```

Console Output:
```
Installing to-base64@0.5.0 to C:\Users\user\.atom\packages failed

> oniguruma@6.1.1 install C:\Users\user\AppData\Local\Temp\apm-install-dir-1161027-4104-112pu99\node_modules\to-base6
ode_modules\oniguruma
> node-gyp rebuild


C:\Users\user\AppData\Local\Temp\apm-install-dir-1161027-4104-112pu99\node_modules\to-base64\node_modules\oniguruma>i
ot defined npm_config_node_gyp (node "C:\Users\user\AppData\Local\atom\app-1.12.5\resources\app\apm\node_modules\npm\
\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\user\AppData\Local\atom\a
1.12.5\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Fram
rk 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it
installed elsewhere.  [C:\Users\user\AppData\Local\Temp\apm-install-dir-1161027-4104-112pu99\node_modules\to-base64\n
_modules\oniguruma\build\binding.sln]
C:\Users\user\AppData\Local\Temp\apm-install-dir-1161027-4104-112pu99
`-- (empty)


npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\user\AppData\Local\atom\app-1.12.5\resources\app\apm\node_modules
de-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\user\\AppData\\Local\\atom\\app-1.12.5\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\
r\\AppData\\Local\\atom\\app-1.12.5\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user\AppData\Local\Temp\apm-install-dir-1161027-4104-112pu99\node_modules\to-base64\node_module
niguruma
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\user\AppData\Local\Temp\apm-install-dir-1161027-410
12pu99\package.json'
npm WARN apm-install-dir-1161027-4104-112pu99 No description
npm WARN apm-install-dir-1161027-4104-112pu99 No repository field.
npm WARN apm-install-dir-1161027-4104-112pu99 No README data
npm WARN apm-install-dir-1161027-4104-112pu99 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\user\\AppData\\Local\\atom\\app-1.12.5\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\use
AppData\\Local\\atom\\app-1.12.5\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\User
user\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\user\\.atom\\.apmrc" "install" "C:\\Users\\user\\AppData\\Local
emp\\d-1161027-4104-1o0mg53\\package.tgz" "--runtime=electron" "--target=1.3.9" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@6.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oniguruma@6.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oniguruma
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\AppData\Local\Temp\apm-install-dir-1161027-4104-112pu99\npm-debug.log
npm ERR! code 1
```

**Comment by fentas** [comment]
Hey,
thanks for reporting. I updated all dependencies and everything seems to work fine.
Try updating to v0.5.1. (just updated it)

If it still does not work, let me know.

**Comment by brusser** [comment]
Still not working for me. Should I be updating something?

**Comment by fentas** [comment]
Have you updated to v0.5.1? 
Have you tried to reinstall?
Is it the same error message?

I have the same version only on linux and everything works fine. :/

**Comment by aplum** [comment]
I had a similar error while trying to install v0.5.1 on my Windows 10 system. Based on [this comment](https://github.com/nodejs/node-gyp/issues/629#issuecomment-225578519), I installed the [VC++ Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools) (default installation), after which installing v0.5.1 worked fine.

I was also having another error before this one, due to not having Python 2.x installed.

**Comment by bjmiller** [comment]
I have a the same issue installing or updating to 0.5.1 .  I'm using OSX 10.11.6 El Capitan, and atom-beta 1.13.0-beta6.  The issue is that oniguruma won't compile.

```
make: *** No rule to make target `../../../../../../../../../../../../Applications/Atom', needed by `Makefile'.  Stop.
```

**Comment by seanpoh** [comment]
Hey there, I also have the same issue on my Windows 10 system. The error is exactly the same as what brusser posted.

Edit (10/12/2016): it works now

**Comment by fentas** [comment]
Sorry for closing/reopening.
I removed the highlighting for now. (that should be the package with oniguruma)
Please try if it's now working (`v0.5.2`).

**Comment by aplum** [comment]
On my system that had v0.5.1 installed, I tried updating to v0.5.2:
```
Updating to “to-base64@0.5.2” failed.
EPERM: operation not permitted, unlink 'C:\Users\alexp\.atom\packages\to-base64\node_modules\oniguruma\build\Release\onig_scanner.node'
```

I restarted Atom, and then to-base64 showed its version as "undefined" under Installed Packages. So I uninstalled to-base64, restarted Atom again, and then installing to-base64 v0.5.2 worked fine.
